PROGRAM MAIN
    USE IOSTREAM
    IMPLICIT NONE
    REAL :: h0A, p0A, T0A, h0B, p0B, T0B
    CHARACTER (LEN=500) :: INPUT_FILENAME_A, INPUT_FILENAME_B, OUTPUT_FILENAME_A, OUTPUT_FILENAME_B
    CHARACTER (LEN=500) :: INTESTAZIONE_A, INTESTAZIONE_B
    CHARACTER (LEN=500) :: msg
    LOGICAL :: ERROR
    INTEGER :: IO, NumberOfLinesA, NumberOfLinesB, position1, position2, position3
    NAMELIST /Files/ INPUT_FILENAME_A, INPUT_FILENAME_B, OUTPUT_FILENAME_A, OUTPUT_FILENAME_B

    !LETTURA NAMELIST
    OPEN(UNIT=20, FILE='input.nml', STATUS='OLD', ACTION='READ', IOSTAT=IO, iomsg=msg)
    IF(IO>0) STOP msg
    READ(20,NML=Files, IOSTAT=IO, iomsg=msg)
    IF(IO>0) STOP msg

    !APRO I FILE
    CALL OPEN_INPUT_FILE(21, INPUT_FILENAME_A, ERROR)
    IF(ERROR) STOP 'ERROR OPENING INPUT FILE A'
    CALL OPEN_INPUT_FILE(22, INPUT_FILENAME_B, ERROR)
    IF(ERROR) STOP 'ERROR OPENING INPUT FILE B'
    CALL OPEN_OUTPUT_FILE(23, OUTPUT_FILENAME_A, ERROR)
    IF(ERROR) STOP 'ERROR OPENING OUTPUT FILE A'
    CALL OPEN_OUTPUT_FILE(24, OUTPUT_FILENAME_B, ERROR)
    IF(ERROR) STOP 'ERROR OPENING OUTPUT FILE B'

    !CONTO RIGHE E CONTROLLO INTEGRITA'
    CALL COUNT_LINES(21, NumberOfLinesA, ERROR)
    IF(ERROR) STOP 'ERROR COUNTING LINES IN INPUT FILE A'
    REWIND(21)

    CALL COUNT_LINES(22, NumberOfLinesB, ERROR)
    IF(ERROR) STOP 'ERROR COUNTING LINES IN INPUT FILE B'
    REWIND(22)

    !LEGGO INTESTAZIONE
    READ(21,'(A)',IOSTAT=IO) INTESTAZIONE_A
    IF(IO>0) STOP 'ERROR READING INPUT FILE A'
    READ(22,'(A)',IOSTAT=IO) INTESTAZIONE_B
    IF(IO>0) STOP 'ERROR READING INPUT FILE B'

    !CERCO h0,p0, T0 NELL'INTESTAZIONE
    position1 = INDEX(INTESTAZIONE_A, 'h0')
    position2 = INDEX(INTESTAZIONE_A, 'p0')
    position3 = INDEX(INTESTAZIONE_A, 'T0')
    READ(INTESTAZIONE_A(position1+3:position2-1),*) h0A
    READ(INTESTAZIONE_A(position2+3:position3-1),*) p0A
    READ(INTESTAZIONE_A(position3+3:LEN_TRIM(INTESTAZIONE_A)),*) T0A
    
    position1 = INDEX(INTESTAZIONE_B, 'h0')
    position2 = INDEX(INTESTAZIONE_B, 'p0')
    position3 = INDEX(INTESTAZIONE_B, 'T0')
    READ(INTESTAZIONE_B(position1+3:position2-1),*) h0B
    READ(INTESTAZIONE_B(position2+3:position3-1),*) p0B
    READ(INTESTAZIONE_B(position3+3:LEN_TRIM(INTESTAZIONE_B)),*) T0B

    !SCRIVO DATI STAZIONE A TEMRINALE
    WRITE(*,'(A19,A10)') 'Dati file stazione: ', TRIM(INPUT_FILENAME_A)
    WRITE(*,'(3(A5,F7.1))') 'h0 =', h0A, ' p0 =', p0A, ' T0 =', T0A
    WRITE(*,'(A19,A10)') 'Dati file stazione: ', TRIM(INPUT_FILENAME_B)
    WRITE(*,'(3(A5,F7.1))') 'h0 =', h0B, ' p0 =', p0B, ' T0 =', T0B

    !CHIUDO I FILE
    CLOSE(21)
    CLOSE(22)
    CLOSE(23)
    CLOSE(24)

END PROGRAM MAIN
