PROGRAM MAIN
    USE IOSTREAM
    IMPLICIT NONE
    CHARACTER (LEN=200) :: INPUT_FILENAME1='a', INPUT_FILENAME2, OUTPUT_FILENAME1, OUTPUT_FILENAME2
    CHARACTER (LEN=200) :: INTESTAZIONE1, INTESTAZIONE2,msg
    INTEGER :: i, position1, position2, position3,NumberOfLines
    REAL :: h01, p01, T01, h02, p02, T02, z
    REAL, PARAMETER :: R = 287.058, g = 9.81
    LOGICAL :: ERROR
    INTEGER :: IO
    REAL, DIMENSION(:,:), ALLOCATABLE :: MATRICE

    NAMELIST /Files/ INPUT_FILENAME1, INPUT_FILENAME2, OUTPUT_FILENAME1, OUTPUT_FILENAME2

    !LETTURA NAMELIST
    OPEN(UNIT=24, FILE='input.nml', STATUS='OLD', ACTION='READ', IOSTAT=IO)
    IF(IO>0) STOP 'ERROR OPENING NAMELIST FILE'
    READ(24,NML=Files, IOSTAT=IO, iomsg=msg)
    IF(IO>0) STOP msg

    !APRO I FILE
    CALL OPEN_INPUT_FILE(20, INPUT_FILENAME1, ERROR)
    IF(ERROR) STOP 'ERROR OPENING INPUT FILE 1'
    CALL OPEN_INPUT_FILE(21, INPUT_FILENAME2, ERROR)
    IF(ERROR) STOP 'ERROR OPENING INPUT FILE 2'
    CALL OPEN_OUTPUT_FILE(22, OUTPUT_FILENAME1, ERROR)
    IF(ERROR) STOP 'ERROR OPENING OUTPUT FILE 1'
    CALL OPEN_OUTPUT_FILE(23, OUTPUT_FILENAME2, ERROR)
    IF(ERROR) STOP 'ERROR OPENING OUTPUT FILE 2'

    !LEGGO INTESTAZIONI COME STRINGA
    READ(20,'(A)',IOSTAT=IO) INTESTAZIONE1
    IF(IO/=0) STOP 'ERROR READING INPUT FILE 1'
    READ(21,'(A)',IOSTAT=IO) INTESTAZIONE2
    IF(IO/=0) STOP 'ERROR READING INPUT FILE 2'

    !CERCO h0,p0, T0 NELL'INTESTAZIONE
    position1 = INDEX(INTESTAZIONE1, 'h0')
    position2 = INDEX(INTESTAZIONE1, 'p0')
    position3 = INDEX(INTESTAZIONE1, 'T0')
    READ(INTESTAZIONE1(position1+3:position2-1),*) h01
    READ(INTESTAZIONE1(position2+3:position3-1),*) p01
    READ(INTESTAZIONE1(position3+3:LEN_TRIM(INTESTAZIONE1)),*) T01

    position1 = INDEX(INTESTAZIONE2, 'h0')
    position2 = INDEX(INTESTAZIONE2, 'p0')
    position3 = INDEX(INTESTAZIONE2, 'T0')
    READ(INTESTAZIONE2(position1+3:position2-1),*) h02
    READ(INTESTAZIONE2(position2+3:position3-1),*) p02
    READ(INTESTAZIONE2(position3+3:LEN_TRIM(INTESTAZIONE2)),*) T02

    !SCRIVO DATI STAZIONE A TEMRINALE CON FORMATO CORRETTO (FLOAT)
    WRITE(*,'(A19,A10)') 'Dati file stazione: ', INPUT_FILENAME1
    WRITE(*,'(3(A5,F7.1))') 'h0 =', h01, ' p0 =', p01, ' T0 =', T01
    WRITE(*,'(A19,A10)') 'Dati file stazione: ', INPUT_FILENAME2
    WRITE(*,'(3(A5,F7.1))') 'h0 =', h02, ' p0 =', p02, ' T0 =', T02
    WRITE(*,*)

    !RIPEMPO MATRICE
    CALL COUNT_LINES(20,NumberOfLines, ERROR)
    IF(ERROR) STOP 'ERROR READING INPUT FILE 1'
    ALLOCATE(MATRICE(NumberOfLines,3))
    REWIND(20)
    CALL SKIP_LINE(20,1, ERROR)
    DO i=1,NumberOfLines
        READ(20,*) MATRICE(i,1), MATRICE(i,2)
    END DO

    !CALCOLO z
    DO i=1,NumberOfLines
        z = h01 + (R/g)*(T01 - MATRICE(i,2))*(LOG(p01) - LOG(MATRICE(i,1))) !DA CONTROLLARE
        MATRICE(i,3) = z
    END DO

    !SCRIVO SU FILE 3 colonne
    DO i = 1,NumberOfLines
        WRITE(22,'(3(F7.1))') MATRICE(i,1), MATRICE(i,2), MATRICE(i,3)
    END DO

    !CHIUDO I FILE
    CLOSE(20)
    CLOSE(21)
    CLOSE(22)
    CLOSE(23)

END PROGRAM MAIN
