PROGRAM MAIN
    USE IOSTREAM

    IMPLICIT NONE
    CHARACTER (LEN=200) :: INPUT_FILENAME1, INPUT_FILENAME2, OUTPUT_FILENAME1, OUTPUT_FILENAME2
    CHARACTER (LEN=200) :: INTESTAZIONE1, INTESTAZIONE2,msg
    INTEGER :: i, position1, position2, position3
    INTEGER :: NumberOfLines1, NumberOfLines2
    REAL :: h01, p01, T01, h02, p02, T02, Tmedia
    REAL, PARAMETER :: R = 287.058, g = 9.80665
    LOGICAL :: ERROR
    INTEGER :: IO
    REAL, ALLOCATABLE, DIMENSION(:,:) :: DATA1, DATA2

    NAMELIST /Files/ INPUT_FILENAME_A, INPUT_FILENAME_B, OUTPUT_FILENAME_A, OUTPUT_FILENAME_B

    !LETTURA NAMELIST
    OPEN(UNIT=24, FILE='input.nml', STATUS='OLD', ACTION='READ', IOSTAT=IO)
    IF(IO>0) STOP 'ERROR OPENING NAMELIST FILE'
    READ(24,NML=Files, IOSTAT=IO, iomsg=msg)
    IF(IO>0) STOP msg

    !APRO I FILE
    CALL OPEN_INPUT_FILE(20, INPUT_FILENAME1, ERROR)
    IF(ERROR) STOP 'ERROR OPENING INPUT FILE 1'
    CALL OPEN_INPUT_FILE(21, INPUT_FILENAME2, ERROR)
    IF(ERROR) STOP 'ERROR OPENING INPUT FILE 2'
    CALL OPEN_OUTPUT_FILE(22, OUTPUT_FILENAME1, ERROR)
    IF(ERROR) STOP 'ERROR OPENING OUTPUT FILE 1'
    CALL OPEN_OUTPUT_FILE(23, OUTPUT_FILENAME2, ERROR)
    IF(ERROR) STOP 'ERROR OPENING OUTPUT FILE 2'

    !LEGGO INTESTAZIONI COME STRINGA
    READ(20,'(A)',IOSTAT=IO) INTESTAZIONE1
    IF(IO/=0) STOP 'ERROR READING INPUT FILE 1'
    READ(21,'(A)',IOSTAT=IO) INTESTAZIONE2
    IF(IO/=0) STOP 'ERROR READING INPUT FILE 2'

    !CERCO h0,p0, T0 NELL'INTESTAZIONE
    position1 = INDEX(INTESTAZIONE1, 'h0')
    position2 = INDEX(INTESTAZIONE1, 'p0')
    position3 = INDEX(INTESTAZIONE1, 'T0')
    READ(INTESTAZIONE1(position1+3:position2-1),*) h01
    READ(INTESTAZIONE1(position2+3:position3-1),*) p01
    READ(INTESTAZIONE1(position3+3:LEN_TRIM(INTESTAZIONE1)),*) T01

    position1 = INDEX(INTESTAZIONE2, 'h0')
    position2 = INDEX(INTESTAZIONE2, 'p0')
    position3 = INDEX(INTESTAZIONE2, 'T0')
    READ(INTESTAZIONE2(position1+3:position2-1),*) h02
    READ(INTESTAZIONE2(position2+3:position3-1),*) p02
    READ(INTESTAZIONE2(position3+3:LEN_TRIM(INTESTAZIONE2)),*) T02

    !SCRIVO DATI STAZIONE A TEMRINALE
    WRITE(*,'(A19,A10)') 'Dati file stazione: ', INPUT_FILENAME1
    WRITE(*,'(3(A5,F7.1))') 'h0 =', h01, ' p0 =', p01, ' T0 =', T01
    WRITE(*,'(A19,A10)') 'Dati file stazione: ', INPUT_FILENAME2
    WRITE(*,'(3(A5,F7.1))') 'h0 =', h02, ' p0 =', p02, ' T0 =', T02
    WRITE(*,*)

    !CONTO RIGHE FILE PER ALLOCAZIONI
    CALL COUNT_LINES(20, NumberOfLines1, ERROR)
    IF(ERROR) STOP 'ERROR COUNTING LINES IN INPUT FILE 1'
    REWIND(20)
    ALLOCATE(DATA1(NumberOfLines1+1, 3))
    CALL COUNT_LINES(21, NumberOfLines2, ERROR)
    IF(ERROR) STOP 'ERROR COUNTING LINES IN INPUT FILE 2'
    REWIND(21)
    ALLOCATE(DATA2(NumberOfLines2+1, 3))
    
    !LETTURA DATI (LOOP)
    DATA1(1,1) = h01
    DATA1(1,2) = p01
    DATA1(1,3) = T01
    DO i=2,NumberOfLines1+1
        READ(20,*) DATA1(i,2), DATA1(i,3)
    END DO
    DO i=2,NumberOfLines2+1
        READ(21,*) DATA2(i,2), DATA2(i,3)
    END DO

    !CALCOLO Z CON FORMULA BAROMETRICA DI LAPLACE
    DO i=2,NumberOfLines1+1
        Tmedia = (DATA1(i-1,3) + DATA1(i,3)) / 2
        DATA1(i,1) = DATA1(i-1,1) + (R/g) * Tmedia * LOG( DATA1(i-1,2)/DATA1(i,2) )
    END DO

    DO i=2,NumberOfLines2+1
        Tmedia = (DATA2(i-1,3) + DATA2(i,3)) / 2
        DATA2(i,1) = DATA2(i-1,1) + (R/g) * Tmedia * LOG( DATA2(i-1,2)/DATA2(i,2) )
    END DO

    !SCRIVO IN OUTPUT
    WRITE(22,'(A)') INTESTAZIONE1
    WRITE(23,'(A)') INTESTAZIONE2
    DO i=1,NumberOfLines1+1
        WRITE(22,'(3(F7.1))') DATA1(i,1), DATA1(i,2), DATA1(i,3)
    END DO
    DO i=1,NumberOfLines2+1
        WRITE(23,'(3(F7.1))') DATA2(i,1), DATA2(i,2), DATA2(i,3)
    END DO

    !CHIUDO I FILE
    CLOSE(20)
    CLOSE(21)
    CLOSE(22)
    CLOSE(23)

END PROGRAM MAIN

